spring:
  application:
    name: bridgefund-assistance-portal
  jackson:
    default-property-inclusion: non_null

server:
  port: ${PORT:8086}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
